#server:
#  port: 8081
#
#spring:
#  datasource:
#    username: root
#    password: Stefan0987
#    url: jdbc:mysql://localhost/department_db?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#      format_sql: true
#      use_sql_comments: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  application:
#    name: EMPLOYEE-SERVICE
#
#eureka:
#  instance:
#    client:
#      serverUrl:
#        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        register-health-indicator: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED


resilience4j.retry:
  instances:
    EMPLOYEE-SERVICE:
      max-attempts: 10
      wait-duration: 2s




